config/routes.rb
Kitshare::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    resources :users, except: [:index]
  end

  resources :kits do
  end

  resources :users do
    resources :endorsements, only: [:create, :update, :destroy]
  end

  resources :charges

  root :to => "pages#home"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/kit.rb
class Kit < ActiveRecord::Base

  #attributes
  attr_accessible :user, :category, :kind, :sub_kind, :title, :daily_price, :weekly_price, :monthly_price, :condition, :description, :insurance_required, :location, :photo1, :photo2, :photo3, :photo4, :photo5, :longtitude, :latitude

  #geocoder
  geocoded_by :location
  after_validation :geocode, :if => :location_changed?

  #validations
  validates :category, :presence => {:message => 'Please input a category'}
  validates :kind, :presence => {:message => 'Please input a type'}
  

  #ownership
  has_many :rentals
  has_many :kit_ratings, dependent: :destroy
  has_many :kit_photos, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :kit_photos

end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
  #stuff for cancancan
  # load_and_authorize_resource
  # before_filter :authenticate_user!, except: [:index, :show]

  # GET /users
  # GET /users.json
  def index
    @kits = Kit.all
    
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @kits }
    end
  end

  def show
    @kit = Kit.find params[:id]

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @kit }
    end
  end

  def new
    @kit = Kit.new
  end

  def create
    @kit = Kit.new(params[:kit])
    @kit.user = current_user
    respond_to do |format|
      if @kit.save
        if params[:kit_photos]
          params[:kit_photos].each do |picture|
            @kit.kit_photos.create(image: picture)
            
          end

        end
        format.html { redirect_to @kit, notice: 'Kit was successfully created.' }

      else
        format.html { render action: "new" }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @kit = Kit.find params[:id]
  end

  def update
    @kit = Kit.find(params[:id])
    
    respond_to do |format|
      if @kit.update_attributes(params[:kit])
        format.html { redirect_to @kit, notice: 'Kit was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def search
  end

end

   

app/views/kits/_form.html.haml
= simple_form_for(@kit) do |f|
  = f.error_notification
  .row
    .row
      %fieldset.field-radius
        %legend.kitshare-blue.field-radius Kit Photos :
        = file_field_tag "kit_photos[]", type: :file, multiple: true

        / light box from Foundation? Need to consider upload as well
    .row{"data-equalizer" => ""}
      .large-6.columns
        .row.collapse
          %fieldset.field-radius{"data-equalizer-watch" => ""}
            %legend.kitshare-blue.field-radius Kit Details:
            .small-3.large-2.columns
              %span.prefix Title
            .small-9.large-10.columns
              = f.text_field :title, autofocus: true
            .small-3.large-2.columns
              %span.prefix Description
            .small-9.large-10.columns  
              = f.text_area :description, :size => '80x10', placeholder: "Optional..."


      .large-6.columns
        .row.collapse
          %fieldset.field-radius{"data-equalizer-watch" => ""}
            %legend.kitshare-blue.field-radius Kit Type:
            .small-3.large-2.columns
              %span.prefix Category
            .small-9.large-10.columns
              = f.select :category, options_for_select(""), prompt: "Select..."
            .small-3.large-2.columns
              %span.prefix Kind
            .small-9.large-10.columns
              = f.select :kind, options_for_select("")
            .small-3.large-2.columns
              %span.prefix Type
            .small-9.large-10.columns
              = f.select :sub_kind, options_for_select("")
            .small-3.large-2.columns
              %span.prefix Condition
            .small-9.large-10.columns
              = f.select :condition, options_for_select(%w{ New Excellent Good Average Poor }), prompt: "Select..."
      
    .row{"data-equalizer" => ""}
      .large-6.columns
        .row.collapse
          %fieldset.field-radius{"data-equalizer-watch" => ""}
            %legend.kitshare-blue.field-radius Pricing details:
            .small-3.large-2.columns
              %span.prefix Daily
            .small-9.large-10.columns
              = f.number_field :daily_price, placeholder: "Daily"
              / needs to be restricted to +ve and exclude characters
            .small-3.large-2.columns
              %span.prefix Weekly
            .small-9.large-10.columns
              = f.number_field :weekly_price, placeholder: "Weekly"
            .small-3.large-2.columns
              %span.prefix Monthly
            .small-9.large-10.columns
              = f.number_field :monthly_price, placeholder: "Monthly"
            .small-4.columns
              %span.prefix Insurance needed?
            .small-8.columns
              = f.check_box :insurance_required
      
      .large-6.columns
        .row.collapse
          %fieldset.field-radius{"data-equalizer-watch" => ""}
            %legend.kitshare-blue.field-radius Kit Location:
            .small-3.large-2.columns
              %span.prefix Address
            .small-9.large-10.columns
              = f.text_field :location


      
  .form-actions
    = f.button :submit, class: "button right"


:javascript
  //<![CDATA[
  $(window).load(function(){
  var data = {
      'Skiing': {
          'Clothes': ["Jacket", "Trousers", "Gloves", "Base layers"],
          'Skis': ["All Mountain", "Race", "Powder"],
          'Bindings': ["N/a"]
      },
      'Snowboarding': {
          'Board': ["Racing", "Park"],
          'Boots': ["Soft", "Hard"]
      }
  },
  $a = $('#kit_category'); // The dropdowns
  $b = $('#kit_kind');
  $c = $('#kit_sub_kind');
   
  for (var prop in data) {
      var first = prop;
      $a.append($("<option>"). // Add options
      attr("value", first).
      text(first));
  }
   
  $a.change(function () {
      var firstkey = $(this).val();
      $b.html(''); // Clear existing options in second dropdown
      for (var prop in data[firstkey]) {
          var second = prop;
          $b.append($("<option>"). // Add options
          attr("value", second).
          text(second));
      }
      $b.change();
  }).change(); // Trigger once to add options at load of first choice
   
  $b.change(function () {
      var firstKey = $a.val(),
          secondKey = $(this).val();
      $c.html(''); // Clear existing options in second dropdown
      for(var i = 0; i < data[firstKey][secondKey].length; i++) {
          var third = data[firstKey][secondKey][i]
          $c.append($("<option>"). // Add options
          attr("value", third).
          text(third));
      }
      $c.change();
  }).change();
  });


  $(document).foundation({
  equalizer : {
    // Specify if Equalizer should make elements equal height once they become stacked.
    equalize_on_stack: false
  }});

app/views/kits/edit.html.haml
%h1 Editing kit

= render 'form'

= link_to 'Show', @kit
\|
= link_to 'Back', kits_path

app/views/kits/index.html.haml
%script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}
%script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
%script{src:"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"}

%body.main-image
  .row.collapse.full-width
    .small-12.small-centered.large-uncentered.large-9.columns
      #map-canvas-global
    .large-3.columns
      %input#autocomplete.controls.text-center{type: :text}
      TEST
      TEST
      TEST


/ making an AJAX request to contact the server to get kit addresses
:javascript

  $(function() {
    $.ajax({
      url: "/kits",
      type: "GET",
      dataType: "json",
      success: function(data) {

        // creating a marker bounds object to use for zooming in to the deepest point in which all of the markers are included 
        var markerBounds = new google.maps.LatLngBounds();

        // iterating through all of my data points
        $.each(data, function(index, kit) {
          // this takes latitude and longitude points and puts it in a LatLon object
          var myLatLng = new google.maps.LatLng(kit.latitude, kit.longitude);
          // this creates a marker that uses the LatLon coordinates to make the marker
          var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
          });
          // when you click on the marker it calls the function that creates the info window (code in map.js)
          google.maps.event.addListener(marker, 'click', function() {
            $.ajax({
              url: '/kits/' + kit.id,
              dataType: "json",
              success: function(data) {
                var string = "<a href='/kits/" + data.id + "'><img src=" + data.photo + " class ='thumbnail'><a/>"
                showWindow(marker, string);
              }
            });
            //var string = "<a href='/kits/" + kit.id + "'><img src='"+ kit.photo.url+"'></a>";
            //showWindow(marker, string);
          });

          // Extend markerBounds with each marker. Essentially saying "hey bounds, include this marker"
          markerBounds.extend(marker.position);
        });

        map.fitBounds(markerBounds);
      }
    });
  });

app/views/kits/new.html.haml
.main-image
	.row
		%br

		= render 'form'

		= link_to 'Back', kits_path

app/views/kits/show.html.haml
%p#notice= notice
.row
  -@kit.kit_photos.each do |p|
    =image_tag p
    


= link_to 'Edit', edit_kit_path(@kit)
\|
= link_to 'Back', kits_path