config/routes.rb
Kitshare::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    resources :users, except: [:index]
  end

  resources :kits do
  end

  resources :users do
    resources :endorsements, only: [:create, :update, :destroy]
  end

  resources :charges

  root :to => "pages#home"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box text-center radius #{name.to_s == 'notice' ? 'info' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
.contain-to-grid
  %nav.top-bar{"data-topbar" => true}
    %ul.title-area        
      %li.name
        = link_to(root_path) do
          %span.logo="KitShare"
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          Menu
    .top-bar-section
      %ul
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
-if current_user
  %ul.right
    %li
      = link_to "Messages", conversations_path
    %li
      = link_to "Add Some Kit", new_kit_path
    %li
      = link_to "Rent Some Kit", kits_path(:view => "new")
    %li.has-dropdown
      = link_to "#{current_user.user_name}", "#"
      %ul.dropdown
        %li
          = link_to(current_user) do
            %span.label.radius.text-center="Reply %:"
            .progress
              %span.meter{:style => "width: #{current_user.replies_percentage}%"}
            .profile-img
              = image_tag(current_user.profile_picture)
            .rating.rating-width 
              #score
                = current_user.rating
            
            
        %li
          = link_to "Payment", "#"
        %li
          = link_to "Other", "#"
        %li
          = link_to "Signout", send("destroy_user_session_path"), method: :delete

    
    

-else
  %ul.right
    %li
      = link_to image_tag("facebook-3-48.png", class: "social-media"), "https://www.facebook.com/Kitshare"
    %li
      = link_to image_tag("twitter-3-48.png", class: "social-media"), "https://twitter.com/kitshare"
    / %li
    /   = link_to "Look around", kits_path(view: "new"), class: "button" 

:javascript
  $('.rating').raty({ readOnly: true, score: parseFloat($('#score').text()) , path: '/assets' });
  $('#score').hide();

app/views/layouts/_profile.html.haml
  .row
    .large-3.columns.header-padding
      .panel.radius.callout
        .text-center
          -if @user.role.present?
            %h4=@user.role
          -if @user == current_user
            %p="Welcome back #{@user.first_name}"
          .profile-img
            -if @user.profile_picture.present?
              = image_tag @user.profile_picture
            -else
              = image_tag "placeholder.png"
          %a.p{"aria-controls" => "drop", "aria-expanded" => "false", "data-dropdown" => "drop", "data-options"=>"align:right"}
            = "#{@user.user_name} &raquo".html_safe
            #drop.f-dropdown.content{"aria-hidden" => "true", "data-dropdown-content" => "", :tabindex => "-1"}
              -if @user.last_3_endorsements.present?
                - @endorsements.each_with_index do |e, i|
                  .rating-hide{:id => "end-rating#{i+1}"}
                    = e["rating"]
                  .rating-show.text-center{:id => "rating#{i+1}"}
                  %strong.text-center= e["title"]
                  .text-center= e["content"]
                  %hr
              -else
                ="#{@user.user_name} has no endorsements yet"
        %hr
        .row
          .label.radius Reply %: 
          .progress
            %span.meter{:style => "width: #{@user.replies_percentage}%"}
          .label.radius Rating:
          %span#user-rating
            #user-score
              = @user.rating

        .row
          .label.radius Has insurance:
          = check_box_tag "" , "" , @user.insurance_end.future? , disabled: true
        -if @user != current_user
          %hr
          .row
            .label.radius="Rented off #{@user.first_name}? Rate them!"
            =form_for [@user, @user.endorsements.build] do |f|
              #given-rating.text-center
              = f.hidden_field :rating, id: "rating", disabled: true
              = f.text_field :title, placeholder: "Title...(extra points for puns)"
              = f.text_area :content, placeholder: "E.g.'#{@user.first_name} was an utter legend!'", size: "30"
              = f.submit "Rate", class: "button radius expand", id: "rate"
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'KitShare'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Kitshare'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:src => "js/foundation/foundation.equalizer.js"}
    = csrf_meta_tags
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:700,900italic|Droid+Sans:400,700", rel: "stylesheet", type: "text/css"

    %meta{content: "width=device-width, user-scalable=no", name: "viewport"}/
    
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
    

    %section    
      = yield

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59464530-1', 'auto');
  ga('send', 'pageview');